# set custom prefix for comands in tmux
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Empezar la numeración de las ventanas en 1
set -g base-index 1
# Empezar la numeración de los paneles en 1
setw -g pane-base-index 1
# Re-numerar ventanas automáticamente al cerrar una
set -g renumber-windows on

# theme 
set -g status-style 'bg=#1e1e2e fg=#cdd6f4' # Catppuccin-style colors
set -g status-right ""

# boot with 3 same tabs, edit if necesarry in the future
# Create windows on startup if they don't exist
# new-window -n "App"
# new-window -n "Nvim"
# new-window -n "Utils"
# new-window -n "Server"
